version: "3.4"

services:
  netmaker: # The Netmaker Server
    container_name: netmaker
    image: gravitl/netmaker:v0.14.0
    volumes: # Volume mounts necessary to store SQL Data, and share data with CoreDNS and MQ (certs folder)
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
      - /root/certs:/etc/netmaker/
    cap_add: # necessary permissions to manage networking
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls: # forwarding enablement for ipv4/ipv6
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    environment:
      SERVER_NAME: "broker.NETMAKER_BASE_DOMAIN" # The resolvable domain of the MQ broker (must point to machine)
      SERVER_HOST: "SERVER_PUBLIC_IP" # the ip of the host machine
      SERVER_API_CONN_STRING: "api.NETMAKER_BASE_DOMAIN:443" # The string used by clients to connect to the api. Includes domain and port.
      COREDNS_ADDR: "SERVER_PUBLIC_IP" # the ip of coredns. Typically the same as SERVER_HOST
      DNS_MODE: "on" # allows netmaker to create a "hosts" file for CoreDNS and send dns records to clients
      SERVER_HTTP_HOST: "api.NETMAKER_BASE_DOMAIN" # The resolvable domain of the api
      API_PORT: "8081" # The port the API is running on
      CLIENT_MODE: "on" # Pretty much always leave this on
      MASTER_KEY: "REPLACE_MASTER_KEY" # The admin master key for accessing the API. Change this in any production installation.
      CORS_ALLOWED_ORIGIN: "*" # The "allowed origin" for API requests. Change to restrict where API requests can come from.
      DISPLAY_KEYS: "on" # Show keys permanently in UI (until deleted) as opposed to 1-time display.
      DATABASE: "sqlite" # The database Netmaker should configure itself for. If not SQLite, need to provide connection details (see above for env vars).
      NODE_ID: "netmaker-server-1" # The ID of the server to identify itself in HA setups and scenarios with multiple Netmaker servers.
      MQ_HOST: "mq" # The name of the MQ container
      HOST_NETWORK: "off"  # whether or not host networking is turned on. Only turn on if configured for host networking (see docker-compose.hostnetwork.yml). Will set host-level settings like iptables.
      VERBOSITY: "1" # Logging verbosity of the server. Can be 0-3
      PORT_FORWARD_SERVICES: "dns"  # set iptables on the machine being managed in order to forward properly from wireguard interface to services listed in "port forward services"
      MANAGE_IPTABLES: "on"  # services for which to configure port forwarding on the machine. 'ssh' forwards port 22 over wireguard, enabling ssh to server over wireguard. dns enables private dns over wireguard.
    ports:
      - "51821-51830:51821-51830/udp" # WireGuard ports - one per network you plan on running
      - "8081:8081" # API port
  netmaker-ui: # The Netmaker UI Component
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.14.0
    links:
      - "netmaker:api"
    ports:
      - "8082:80"
    environment:
      BACKEND_URL: "https://api.NETMAKER_BASE_DOMAIN" # URL where UI will send API requests. Change based on SERVER_HOST, SERVER_HTTP_HOST, and API_PORT
    restart: always
  coredns: # The DNS Server. Remove this section if you dont plan to use the coredns server"
    depends_on:
      - netmaker 
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    volumes:
      - dnsconfig:/root/dnsconfig
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host # Wants ports 80 and 443!
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv # you could also serve a static site in site folder
      - caddy_data:/data
      - caddy_conf:/config
  mq: # the MQTT broker for netmaker
    image: eclipse-mosquitto:2.0.11-openssl
    depends_on:
      - netmaker
    container_name: mq
    restart: unless-stopped
    ports:
      - "127.0.0.1:1883:1883" # only exposed locally
      - "8883:8883" # exposed publicly and must be reachable from all clients!
    volumes:
      - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf # need to pull conf file from github before running (under docker/mosquitto.conf
      - /root/certs/:/mosquitto/certs/ # certs generated by netmaker server, including root certificate and client certs for every peer.
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
volumes:
  caddy_data: {} # storage for caddy data
  caddy_conf: {} # storage for caddy configuration file
  sqldata: {} # storage for embedded sqlite
  dnsconfig: {} # storage for coredns
  mosquitto_data: {} # storage for mqtt data
  mosquitto_logs: {} # storage for mqtt logs